FROM python:3

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY ./mac/requirements.txt /

# Install any needed software
RUN echo "Updating/installing software..." \
  && pip install -r /requirements.txt \
  && echo "Finished."

# Run CMD
CMD [ "python", "-u", "/app/mac.py" ]
